# Generated by Django 4.1.7 on 2023-05-11 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=80)),
                ("image_file", models.FileField(upload_to="image_file/%Y_%m_%d")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 5, 11, 5, 59, 8, 288024, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=100)),
                ("sec_file", models.FileField(upload_to="sec_file/%Y_%m_%d")),
            ],
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("value", models.FloatField()),
                ("created_at", models.DateTimeField()),
            ],
        ),
    ]
