# Generated by Django 4.1.7 on 2023-05-22 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0003_controlaircon_controldehumidifier_controlhumidifier_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="controlhumidifier",
            old_name="humidefiercontrol",
            new_name="humidifiercontrol",
        ),
    ]
