# Generated by Django 4.1.7 on 2023-05-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0004_rename_humidefiercontrol_controlhumidifier_humidifiercontrol"),
    ]

    operations = [
        migrations.AddField(
            model_name="dht_humi",
            name="standard_humi",
            field=models.FloatField(default=55),
        ),
        migrations.AddField(
            model_name="dht_temp",
            name="standard_temp",
            field=models.FloatField(default=24),
        ),
    ]
