# Generated by Django 4.1.7 on 2023-05-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0006_standardhumidity_standardtemperature_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TotalSmartControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("totalcontrol", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="standardhumidity",
            name="standard_humi",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="standardtemperature",
            name="standard_temp",
            field=models.FloatField(),
        ),
    ]
