# Generated by Django 4.1.7 on 2023-05-25 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0007_totalsmartcontrol_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="totalsmartcontrol",
            old_name="totalcontrol",
            new_name="total_control",
        ),
    ]
