# Generated by Django 4.1.7 on 2023-03-16 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="게시글의 제목을 한 줄로 작성하세요.",
                        max_length=200,
                        verbose_name="제목",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="내용을 상세히 작성하세요.", verbose_name="내용"),
                ),
                ("create_date", models.DateTimeField(verbose_name="생성일")),
                ("modify_date", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_board",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("create_date", models.DateTimeField(verbose_name="생성일")),
                ("modify_date", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.board"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClubPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("create_date", models.DateTimeField(verbose_name="생성일")),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.board"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CK", "Cook"),
                            ("CT", "Culture"),
                            ("GA", "Game"),
                            ("LA", "Language"),
                            ("MU", "Music"),
                            ("OD", "Outdoor"),
                            ("SP", "Sports"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("name", models.TextField(verbose_name="클럽이름")),
                (
                    "author",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_club",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="board",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.club"
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="voter",
            field=models.ManyToManyField(
                related_name="voter_board", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
