# Generated by Django 4.1.7 on 2023-03-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="event_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
