# Generated by Django 4.1.7 on 2023-03-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_board_event_date"),
        ("main", "0003_summernoteattachment_alter_board_event_date"),
    ]

    operations = []
