# Generated by Django 4.1.7 on 2023-03-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_merge_20230316_1556"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SummerNoteAttachment",
        ),
    ]
