# Generated by Django 4.1.7 on 2023-06-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_noticeboard_alter_communityboard_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sound_level_verified",
            name="sound_type",
            field=models.CharField(
                choices=[
                    ("충격음", "충격음"),
                    ("가구끄는소리", "가구끄는소리"),
                    ("진공청소기", "진공청소기"),
                    ("악기소리", "악기소리"),
                    ("반려동물", "반려동물"),
                ],
                default="발걸음소리",
                max_length=30,
                verbose_name="소음 종류",
            ),
        ),
    ]
